### ISSUE TITLE
No support for Many-to-Many

### ISSUE THREAD

**Issue by ricefield** [sbaechler/django-scaffolding#7]
Am I mistaken, or is there no support for Many-to-Many fields from this module?

**Comment by sbaechler** [comment]
A Many to Many Scaffold is currently not possible because both sides of the intermediate model need to be existing database entries.

There is a way to do this though:
Specify a concrete intermediate model as described [in the Django docs](https://docs.djangoproject.com/en/1.7/topics/db/models/#intermediary-manytomany). You can then use the scaffolding.ForeignKey to create a scaffold for the intermediate instances.
